apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-service
  template:
    metadata:
      labels:
        app: jenkins-service
    spec:
      containers:
        - name: jenkins-service
          image: jenkins/jenkins:lts
          ports:
            - name: http-port
              containerPort: 8080
            - name: agent-port
              containerPort: 50000
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-data
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: agent
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins-service
