---
- name: Deploy an Application to Kubernetes
  hosts: windows_serveur
  gather_facts: no

  vars:
    app_name: discovery-app
    manifest_path: "{{ playbook_dir }}/discovery-deploy.yaml"
    remote_manifest_path: "C:/temp/discovery-deploy.yaml"

  tasks:

    # ============================================================
    # 1. Créer un répertoire temporaire sur le serveur distant
    # ============================================================
    - name: Ensure C:\temp directory exists
      win_file:
        path: "C:/temp"
        state: directory

    # ============================================================
    # 2. Copier le fichier discovery-deploy.yaml sur le serveur distant
    # ============================================================
    - name: Copy Kubernetes manifest to remote server
      copy:
        src: "{{ manifest_path }}"
        dest: "{{ remote_manifest_path }}"

    # ============================================================
    # 3. Appliquer le manifest Kubernetes sur le cluster
    # ============================================================
    - name: Deploy Kubernetes manifest on remote cluster
      win_command: "kubectl apply -f {{ remote_manifest_path }}"

    # ============================================================
    # 4. Validation des déploiements
    # ============================================================
    - name: Get status of running pods
      win_command: "kubectl get pods"
      register: pod_status

    - name: Display pod status
      debug:
        msg: "Pods Status: {{ pod_status.stdout }}"
