---
- name: Deploy an Application to Kubernetes
  hosts: windows_serveur
  gather_facts: no

  vars:
    app_name: discovery-app
    manifest_path: "discovery-deploy.yaml"

  tasks:

    # ============================================================
    # 1. Appliquer directement le manifest Kubernetes
    # ============================================================
    - name: Deploy Kubernetes manifest on remote cluster
      win_command: "kubectl apply -f {{ manifest_path }}"

    # ============================================================
    # 2. Validation des déploiements
    # ============================================================
    - name: Get status of running pods
      win_command: "kubectl get pods "
      register: pod_status

    - name: Display pod status
      debug:
        msg: "Pods Status: {{ pod_status.stdout }}"
