---
- name: Deploy an Application to Kubernetes
  hosts: windows_serveur
  gather_facts: no

  vars:
    manifest_path: "{{ playbook_dir }}/discovery-deploy.yaml"

  tasks:
    - name: Deploy Kubernetes manifest using Ansible Kubernetes module
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', manifest_path) }}"

    - name: Get status of running pods
      win_command: "kubectl get pods "
      register: pod_status

    - name: Display pod status
      debug:
        msg: "Pods Status: {{ pod_status.stdout }}"
