- name: Deploy an Application to Kubernetes
  hosts: windows_serveur
  gather_facts: no

  tasks:
    - name: Deploy the Application using Deployment manifest
      win_command:
        cmd: "kubectl apply -f discovery-deploy.yaml"

    - name: Confirm Application Running
      win_command:
        cmd: "kubectl get pods"
      register: pod_status

    - name: Print Pod Status
      debug:
        msg: "Pod Status: {{ pod_status.stdout }}"
