- name: Deploy Kubernetes manifest using kubectl on Windows
  hosts: windows_serveur
  gather_facts: no

  tasks:
    - name: Ensure kubectl is installed
      win_command: kubectl version --client
      register: kubectl_installed
      ignore_errors: yes

    - name: Deploy Kubernetes manifest
      win_command: "kubectl apply -f discovery-deploy.yaml"

