- name: Deploy an Application to Kubernetes
  hosts: windows_serveur
  gather_facts: no

  tasks:
    - name: Copy Kubernetes manifest to remote server
      copy:
        src: ./discovery-deploy.yaml
        dest: /tmp/discovery-deploy.yaml

    - name: Deploy Kubernetes manifest on remote cluster
      command: "kubectl apply -f /tmp/discovery-deploy.yaml"

    - name: Get status of running pods
      command: "kubectl get pods "
      register: pod_status

    - name: Display pod status
      debug:
        msg: "Pods Status: {{ pod_status.stdout }}"
