- name: Deploy Kubernetes Deployment without kubeconfig
  hosts: windows_serveur
  gather_facts: no

  tasks:

    - name: Deploy Kubernetes manifest
      kubernetes.core.k8s:
        state: present
        definition: "discovery-deploy.yaml"
      register: deployment_result

    - name: Display deployment result
      debug:
        msg: "Deployment result: {{ deployment_result }}"
