
- name: Deploy an Application to Kubernetes
  hosts: windows_serveur
  gather_facts: no

  tasks:
    - name: Deploy the Application using Deployment manifest
      command: "kubectl apply -f discovery-deploy.yaml"

    - name: Confirm Application Running
      command: "kubectl get pods "
      register: pod_status

    - name: Print Pod Status
      debug:
        msg: "{{ pod_status.stdout }}"
